### ISSUE TITLE
Llama 3 always emits <|eot_id|> as part of the result.

### ISSUE THREAD

**Issue by actow** [ShenghaiWang/SwiftLlama#4]
Ideally the stop token should NOT be included in the result.

**Comment by ShenghaiWang** [comment]
By design, I want to get this covered via configuring stop tokens. Please refer to this file. https://github.com/ShenghaiWang/SwiftLlama/blob/main/Sources/SwiftLlama/Models/StopToken.swift

I haven't had time to go through the prompt styles for different models and fully test this logic though. Will take a look when have time. Thanks for your contribution.

**Comment by actow** [comment]
Yes. I did set the correct stop token in the configuration.

The right way forward is to add unit test for class SwiftLlama with a fake model that emits llama 3 tokens. That way we can easily reproduce this and fix it, and stop regression.
